name: release

on:
  push: 
    branches:
      - '**' # Activa el workflow solo en push de tags

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }} # Toma el nombre del tag del evento
